### ISSUE TITLE
Installation of workers appears to fail

### ISSUE THREAD

**Issue by colinmutter** [aws-quickstart/quickstart-confluent-kafka#33]
A fresh install of CP Open Source (master template, new VPC) using the Amazon Linux AMI shows the workers' installation fails with:

```
[ec2-user@ip-xx-xx-xx-xx ~]$ cat /tmp/cp-install.err
/var/lib/cloud/instance/scripts/part-001: line 73: /tmp/sbin/cp-install.sh: No such file or directory
[ec2-user@ip-xx-xx-xx-xx ~]$ cat /tmp/cp-deploy.err
/var/lib/cloud/instance/scripts/part-001: line 74: /tmp/sbin/cp-deploy.sh: No such file or directory
```

```
[ec2-user@ip-xx-xx-xx-xx ~]$ tail /var/log/cloud-init.log
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 127
Reason: -
Stdout: ''
Stderr: ''
Jul 10 18:56:02 cloud-init[2811]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jul 10 18:56:02 cloud-init[2811]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Jul 10 18:56:02 cloud-init[2811]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 660, in _run_modules
    cc.run(run_name, mod.handle, func_args, freq=freq)
  File "/usr/lib/python2.7/dist-packages/cloudinit/cloud.py", line 63, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/dist-packages/cloudinit/helpers.py", line 197, in run
    results = functor(*args)
  File "/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 651, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands
```

Using default configuration options.

**Comment by colinmutter** [comment]
Update: tracked this down to an unhandled cfn-init failure @ this command in the user-data 

https://github.com/aws-quickstart/quickstart-confluent-kafka/blob/master/templates/nodegroup.template#L942

Confirmed by observing a network error in cfn-init.log
```
[ec2-user@ip-xx-xx-xx-xx ~]$ sudo cat /var/log/cfn-init.log
2017-07-10 18:55:25,523 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2017-07-10 18:55:25,523 [DEBUG] Signaling resource Nodes in stack kafka-cluster-ConfluentStack-SOF6C25AW0JT-WorkerStack-GI45DGSQAT8D with unique ID i-02abbefa893d82717 and status SUCCESS
2017-07-10 18:55:25,813 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2017-07-10 18:55:25,813 [DEBUG] Describing resource NodeLaunchConfig in stack kafka-cluster-ConfluentStack-SOF6C25AW0JT-WorkerStack-GI45DGSQAT8D
2017-07-10 18:55:59,453 [ERROR] SSLError
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```

More error handling in the user-data may need to be added to ensure a failure bubbles up to CF to  fail the stack creation.

**Comment by kamarja** [comment]
Thank you for reporting this, we will look into it.

**Comment by santiagocardenas** [comment]
@dbtucker Have you run into this?

**Comment by dbtucker** [comment]
The only time I've ever seen it is in development when I've failed to properly stage the set of files downloaded by cfn-init (eg the permissions were wrong, I had forgotten to place one in the bucket, etc.)   I've never seen it with the production version of the template.

Is there some error handling that should be done with cfn-init ?   My other "download artifacts" scripts have some retries (and a backoff) programmed in to deal with intermittent network errors.

**Comment by esetnik** [comment]
Note that i'm seeing the same issue bootstrapping an ECS instance using CloudFormation and `cfn-init`, when following the example [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-efs.html). This error you're seeing is likely not directly related to this particular quickstart. It seems to be a more widespread issue.

```
$ cat /var/log/cfn-init.log 
2017-08-08 01:20:37,114 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2017-08-08 01:20:37,114 [DEBUG] Describing resource EcsInstanceLc in stack xxx-stack
2017-08-08 01:21:07,743 [ERROR] SSLError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 162, in _retry
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 234, in _timeout
    raise exc[0]
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```

user-data:
```          
yum install -y aws-cfn-bootstrap
/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EcsInstanceLc --configsets MountConfig --region ${AWS::Region}
crontab /home/ec2-user/crontab
/opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EcsInstanceAsg --region ${AWS::Region}
```

metadata:
```
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          MountConfig:
          - setup
          - mount
        setup:
          packages:
            yum:
              nfs-utils: []
        mount:
          commands:
            01_createdir:
              command: !Sub "mkdir -p ${MountPoint}"
            02_mount:
              command: !Sub >
                mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${FileSystem}.efs.${AWS::Region}.amazonaws.com:/ ${MountPoint}
            04_fstab:
              command: !Sub >
                echo -e "${FileSystem}.efs.${AWS::Region}.amazonaws.com:/ \t\t ${MountPoint} \t\t nfs \t\t nfsvers=4.1,rsize=1048576,wsize=1048576,soft,timeo=600,retrans=2 \t\t 0 \t\t 0" | tee -a /etc/fstab
            03_permissions:
              command: !Sub "chown ec2-user:ec2-user ${MountPoint}"
```
