### ISSUE TITLE
Issue writing from Spark to Confluent Kafka Enterprise

### ISSUE THREAD

**Issue by bobby259** [aws-quickstart/quickstart-confluent-kafka#34]
We have configured a Confluent Kafka Cluster on our AWS Account. We have the Databricks Platform (Spark) running in a VPC say VPC1 and Kafka Cluster running in another VPC say VPC2. We have established a VPC Peering connection between VPC1 and VPC2. But, we are unable to write to our Kafka Cluster from Databricks Spark Platform. We are facing time-out issues:

`Caused by: kafkashaded.org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.`

What could be a fix for this? Please help.

P.S: I strongly believe that VPC peering has been set-up without issues as we have ElasticSearch running in the same VPC as Kafka and we are able to write to Elasticsearch cluster without any issues but not to Kafka Cluster.

**Comment by dbtucker** [comment]
Can you do the following simple check 
   Install the core confluent software on one of the nodes in the Spark VPC (VPC1) and 
   check whether the simple tools work
     kafka-topics --zookeeper <cp-zk-host>:2181 --list
     kafka-console-consumer --new-consumer --bootstrap-server <cp-broker-host>:9092 --topic --max-message 10

I suspect that the issue is hostname resolution.   You might have to figure out what the resolvable address of the Confluents hosts are within VPC1 and make sure that the proper ports are open.   By default, the 2181 and 9092 ports may not be open from VPC1 into the Confluent VPC.

**Comment by bobby259** [comment]
I have installed confluent software on one of the nodes from VPC1 and executed the scripts and the result was as below:
```
# kafka-topics --zookeeper :2181 --list
__consumer_offsets
_schemas
# kafka-console-consumer --new-consumer --bootstrap-server 9092 --topic --max-message 10
[2017-07-11 20:37:26,122] ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$)
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:718)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:597)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:579)
        at kafka.consumer.NewShinyConsumer.<init>(BaseConsumer.scala:53)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:69)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:50)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: 9092
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:45)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:654)
        ... 6 more

```

And yes, as you said when we are unable to resolve the hostnames but when I checked the NACLs of our VPC they are open for all the ports (both outbound of Databricks VPC and Inbound of Kafka's VPC are open for all the ports).
One thing, I dont have Elastic IPs assigned to Kafka nodes, do you think this could be an issue? Please help..
